Reworked attributes system for better experience
AleXr64/Telegram-bot-framework pull request #47
Opened 2021-07-20 16:16 UTC by voed

2021-07-22 08:50 UTC, AleXr64 requested changes

2021-07-22 08:50 UTC, AleXr64 commented on TGBotFramework/BotFramework/Bot.cs
> +            Console.WriteLine(exception);
Перезапуск сработает?

2021-07-22 08:50 UTC, AleXr64 commented on TGBotFramework/BotFramework/BotEventHandler.cs
> -                if(executed) return;
Мультивызов хандлеров?

2021-07-22 08:50 UTC, AleXr64 commented on TGBotFramework/BotFramework/Bot.cs
> +                await client.DeleteWebhookAsync(cancellationToken:cancellationToken);
Наверное, надо всегда пытаться хук снять: если хук висит, даже поллинг не заработает - апи отлупнет

2021-07-22 08:50 UTC, AleXr64 commented on .github/workflows/main.yml
> -name: .NET Core
Может, есть смысл пушить нугет только при билде мастера и беты? Посмотри build.cake

2021-07-23 14:41 UTC, voed commented on TGBotFramework/BotFramework/BotEventHandler.cs
> -                if(executed) return;
Игрался и забыл вернуть)

2021-07-23 14:42 UTC, voed commented on TGBotFramework/BotFramework/Bot.cs
> +            Console.WriteLine(exception);
Не тестил, проверю

2021-07-25 16:19 UTC, voed commented on .github/workflows/main.yml
> -name: .NET Core
Сделаю отдельным коммитом

2021-07-25 18:38 UTC, AleXr64 approved these changes

2021-07-25 18:39 UTC, merged