add handle NewChatMembers and LeftChatMember
AleXr64/Telegram-bot-framework pull request #73
Opened 2021-09-04 17:11 UTC by azhe403

With this PR, we can handle new member or left member on Chat

This about a snippet code

```
[Message(InChat.All, MessageFlag.HasNewChatMembers)]
public async Task NewMember()
{
   await Bot.SendTextMessageAsync(Chat, "Welcome!");
}

[Message(InChat.All, MessageFlag.HasLeftChatMember)]
public async Task LeftMember()
{
   await Bot.SendTextMessageAsync(Chat, "Good bye!");
}
```
Thanks!

2021-09-04 21:32 UTC, voed requested changes

2021-09-04 21:32 UTC, voed commented on TGBotFramework/BotFramework/Enums/MessageFlag.cs
>          All = HasForward |
Add it to `All` flag.

2021-09-04 21:32 UTC, voed commented on TGBotFramework/BotFramework/Attributes/MessageAttribute.cs
> +                        MessageFlag.HasNewChatMembers => message.NewChatMembers != null,
NewChatMembers is array, so i think we also need to check element count in this array, just in case.

2021-09-05 11:16 UTC, voed requested changes
Change this and i will merge it

2021-09-05 11:16 UTC, voed commented on TGBotFramework/BotFramework/Attributes/MessageAttribute.cs
> +                        MessageFlag.HasNewChatMembers => message.NewChatMembers != null && message.NewChatMembers?.Length != 0,
Now you are double checking for null:) 
`MessageFlag.HasNewChatMembers => message.NewChatMembers?.Length != 0` is enough
Or you can use [Any](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.any?view=net-5.0):
`MessageFlag.HasNewChatMembers => message.NewChatMembers?.Any() == true`

2021-09-05 13:15 UTC, azhe403 commented
these file just reformatted by IDE

2021-09-05 18:08 UTC, merged

2021-09-05 18:21 UTC, voed commented
@azhe403 Thanks. It would be great to implement other new types (#74) if you have enough time/motivation.